name: test
on:
  push:
    branches: [master]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: olafurpg/setup-scala@v14
      - name: test
        run: sbt +test
